# Generated by Django 5.1.11 on 2025-06-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together=set(),
        ),
    ]
