# Generated by Django 5.1.11 on 2025-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_joinrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
