export const actuarialResources = [
  // SOA Resources
  {
    id: "soa-1",
    title: "Probability for Risk Management",
    description: "A comprehensive textbook covering the material for SOA Exam P and CAS Exam 1.",
    type: "book",
    organization: "SOA",
    exam: "Exam P - Probability",
    author: "Matthew J. Hassett, Donald G. Stewart",
    coverImage: "/placeholder.svg?text=Probability&height=128&width=96",
    isPremium: true,
    lastUpdated: "January 2023",
  },
  {
    id: "soa-2",
    title: "ASM Study Manual for Exam P",
    description: "Study manual with practice problems and detailed solutions for the SOA Exam P.",
    type: "book",
    organization: "SOA",
    exam: "Exam P - Probability",
    author: "Abraham Weishaus",
    coverImage: "/placeholder.svg?text=ASM&height=128&width=96",
    isPremium: true,
    lastUpdated: "March 2023",
  },
  {
    id: "soa-3",
    title: "Financial Mathematics: A Practical Guide for Actuaries",
    description: "Covers the theory of interest and financial mathematics required for SOA Exam FM.",
    type: "book",
    organization: "SOA",
    exam: "Exam FM - Financial Mathematics",
    author: "Chris Ruckman, Joe Francis",
    coverImage: "/placeholder.svg?text=Financial&height=128&width=96",
    isPremium: true,
    lastUpdated: "February 2023",
  },
  {
    id: "soa-4",
    title: "Exam P Practice Problems",
    description: "Collection of practice problems with solutions for SOA Exam P.",
    type: "revision",
    organization: "SOA",
    exam: "Exam P - Probability",
    author: "Society of Actuaries",
    isPremium: false,
    lastUpdated: "December 2022",
  },
  {
    id: "soa-5",
    title: "Exam FM Sample Questions",
    description: "Official sample questions and solutions for SOA Exam FM.",
    type: "revision",
    organization: "SOA",
    exam: "Exam FM - Financial Mathematics",
    author: "Society of Actuaries",
    isPremium: false,
    lastUpdated: "November 2022",
  },
  {
    id: "soa-6",
    title: "LTAM Past Exam Questions and Solutions",
    description: "Past exam questions with detailed solutions for SOA Exam LTAM.",
    type: "paper",
    organization: "SOA",
    exam: "Exam LTAM - Long-Term Actuarial Mathematics",
    author: "Society of Actuaries",
    isPremium: false,
    lastUpdated: "October 2022",
  },
  {
    id: "soa-7",
    title: "STAM Practice Exam",
    description: "Practice exam with solutions for SOA Exam STAM.",
    type: "paper",
    organization: "SOA",
    exam: "Exam STAM - Short-Term Actuarial Mathematics",
    author: "Society of Actuaries",
    isPremium: false,
    lastUpdated: "September 2022",
  },
  {
    id: "soa-8",
    title: "Loss Models: From Data to Decisions",
    description: "Textbook covering statistical methods for analyzing insurance data.",
    type: "book",
    organization: "SOA",
    exam: "Exam STAM - Short-Term Actuarial Mathematics",
    author: "Stuart A. Klugman, Harry H. Panjer, Gordon E. Willmot",
    coverImage: "/placeholder.svg?text=Loss&height=128&width=96",
    isPremium: true,
    lastUpdated: "April 2023",
  },

  // IFOA Resources
  {
    id: "ifoa-1",
    title: "CS1 Core Reading",
    description: "Official core reading material for the CS1 Actuarial Statistics exam.",
    type: "book",
    organization: "IFOA",
    exam: "CS1 - Actuarial Statistics",
    author: "Institute and Faculty of Actuaries",
    coverImage: "/placeholder.svg?text=CS1&height=128&width=96",
    isPremium: true,
    lastUpdated: "January 2023",
  },
  {
    id: "ifoa-2",
    title: "CS2 Core Reading",
    description: "Official core reading material for the CS2 Risk Modelling and Survival Analysis exam.",
    type: "book",
    organization: "IFOA",
    exam: "CS2 - Risk Modelling and Survival Analysis",
    author: "Institute and Faculty of Actuaries",
    coverImage: "/placeholder.svg?text=CS2&height=128&width=96",
    isPremium: true,
    lastUpdated: "February 2023",
  },
  {
    id: "ifoa-3",
    title: "CM1 Formulae and Tables",
    description: "Essential formulae and tables for the CM1 Actuarial Mathematics exam.",
    type: "revision",
    organization: "IFOA",
    exam: "CM1 - Actuarial Mathematics",
    author: "Institute and Faculty of Actuaries",
    isPremium: false,
    lastUpdated: "March 2023",
  },
  {
    id: "ifoa-4",
    title: "CM2 Past Papers",
    description: "Collection of past papers for the CM2 Financial Engineering and Loss Reserving exam.",
    type: "paper",
    organization: "IFOA",
    exam: "CM2 - Financial Engineering and Loss Reserving",
    author: "Institute and Faculty of Actuaries",
    isPremium: false,
    lastUpdated: "April 2023",
  },
  {
    id: "ifoa-5",
    title: "CS1 Revision Notes",
    description: "Comprehensive revision notes for the CS1 Actuarial Statistics exam.",
    type: "revision",
    organization: "IFOA",
    exam: "CS1 - Actuarial Statistics",
    author: "ActEd",
    isPremium: true,
    lastUpdated: "May 2023",
  },
  {
    id: "ifoa-6",
    title: "CS2 Mock Exam",
    description: "Mock exam with solutions for the CS2 Risk Modelling and Survival Analysis exam.",
    type: "paper",
    organization: "IFOA",
    exam: "CS2 - Risk Modelling and Survival Analysis",
    author: "ActEd",
    isPremium: true,
    lastUpdated: "June 2023",
  },

  // CAS Resources
  {
    id: "cas-1",
    title: "Basic Ratemaking",
    description: "Comprehensive guide to insurance ratemaking principles and techniques.",
    type: "book",
    organization: "CAS",
    exam: "Exam 5 - Basic Ratemaking",
    author: "Geoff Werner, Claudine Modlin",
    coverImage: "/placeholder.svg?text=Ratemaking&height=128&width=96",
    isPremium: false,
    lastUpdated: "January 2023",
  },
  {
    id: "cas-2",
    title: "Foundations of Casualty Actuarial Science",
    description: "Fundamental principles and practices of casualty actuarial science.",
    type: "book",
    organization: "CAS",
    exam: "Exam 1 - Probability",
    author: "Casualty Actuarial Society",
    coverImage: "/placeholder.svg?text=CAS&height=128&width=96",
    isPremium: true,
    lastUpdated: "February 2023",
  },
  {
    id: "cas-3",
    title: "Exam 2 Practice Problems",
    description: "Collection of practice problems with solutions for CAS Exam 2.",
    type: "revision",
    organization: "CAS",
    exam: "Exam 2 - Financial Mathematics",
    author: "Casualty Actuarial Society",
    isPremium: false,
    lastUpdated: "March 2023",
  },
  {
    id: "cas-4",
    title: "Exam 3F Past Papers",
    description: "Past exam papers with solutions for CAS Exam 3F.",
    type: "paper",
    organization: "CAS",
    exam: "Exam 3F - Financial Economics",
    author: "Casualty Actuarial Society",
    isPremium: false,
    lastUpdated: "April 2023",
  },
  {
    id: "cas-5",
    title: "Loss Reserving: An Actuarial Perspective",
    description: "Comprehensive guide to loss reserving techniques for property and casualty insurance.",
    type: "book",
    organization: "CAS",
    exam: "Exam 5 - Basic Ratemaking",
    author: "Ronald F. Wiser",
    coverImage: "/placeholder.svg?text=Reserving&height=128&width=96",
    isPremium: true,
    lastUpdated: "May 2023",
  },
]
