export const simulationModels = [
  {
    id: "ifrs17-liability-model",
    title: "IFRS 17 Liability Valuation",
    description: "Calculate insurance contract liabilities under IFRS 17 standard with CSM and risk adjustment",
    category: "Actuarial",
    categoryColor: "bg-blue-500",
    language: "Python",
    author: {
      name: "Dr. Sarah Chen",
      avatar: "/placeholder.svg?text=SC&height=32&width=32",
    },
    collaborators: 3,
    runtime: "~2 min",
    featured: true,
    tags: ["IFRS 17", "Insurance", "Valuation"],
    lastRun: "2023-12-15",
    popularity: 95,
  },
  {
    id: "climate-var-model",
    title: "Climate Value-at-Risk",
    description: "Assess portfolio climate risk using scenario analysis and transition pathways",
    category: "Climate",
    categoryColor: "bg-green-500",
    language: "R",
    author: {
      name: "Prof. Michael Torres",
      avatar: "/placeholder.svg?text=MT&height=32&width=32",
    },
    collaborators: 2,
    runtime: "~5 min",
    featured: true,
    tags: ["Climate Risk", "VaR", "ESG"],
    lastRun: "2023-12-14",
    popularity: 87,
  },
  {
    id: "monte-carlo-portfolio",
    title: "Monte Carlo Portfolio Simulation",
    description: "Simulate portfolio returns with multiple risk factors and correlation structures",
    category: "Financial",
    categoryColor: "bg-emerald-500",
    language: "Python",
    author: {
      name: "Alex Rodriguez",
      avatar: "/placeholder.svg?text=AR&height=32&width=32",
    },
    collaborators: 4,
    runtime: "~3 min",
    featured: true,
    tags: ["Monte Carlo", "Portfolio", "Risk"],
    lastRun: "2023-12-13",
    popularity: 92,
  },
  {
    id: "mortality-projection",
    title: "Mortality Rate Projection",
    description: "Project future mortality rates using Lee-Carter and Cairns-Blake-Dowd models",
    category: "Actuarial",
    categoryColor: "bg-blue-500",
    language: "R",
    author: {
      name: "Dr. Emma Wilson",
      avatar: "/placeholder.svg?text=EW&height=32&width=32",
    },
    collaborators: 2,
    runtime: "~4 min",
    featured: false,
    tags: ["Mortality", "Demographics", "Projection"],
    lastRun: "2023-12-12",
    popularity: 78,
  },
  {
    id: "pandemic-spread-model",
    title: "Pandemic Spread Simulation",
    description: "Model disease spread using SEIR compartmental models with policy interventions",
    category: "Health",
    categoryColor: "bg-red-500",
    language: "Python",
    author: {
      name: "Dr. James Park",
      avatar: "/placeholder.svg?text=JP&height=32&width=32",
    },
    collaborators: 3,
    runtime: "~6 min",
    featured: false,
    tags: ["Epidemiology", "SEIR", "Public Health"],
    lastRun: "2023-12-11",
    popularity: 83,
  },
  {
    id: "neural-network-pricing",
    title: "Neural Network Insurance Pricing",
    description: "Deep learning model for insurance premium calculation with feature importance",
    category: "Machine Learning",
    categoryColor: "bg-purple-500",
    language: "Python",
    author: {
      name: "Lisa Zhang",
      avatar: "/placeholder.svg?text=LZ&height=32&width=32",
    },
    collaborators: 2,
    runtime: "~8 min",
    featured: false,
    tags: ["Neural Networks", "Pricing", "Deep Learning"],
    lastRun: "2023-12-10",
    popularity: 89,
  },
]
