# Generated by Django 5.1.11 on 2025-06-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
