# Generated by Django 5.1.11 on 2025-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnhub', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/'),
        ),
    ]
