# Generated by Django 5.1.11 on 2025-07-01 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnhub', '0003_course_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
