# Generated by Django 5.0.14 on 2025-06-03 05:48

import django.db.models.deletion
import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(help_text="Unique identifier for the category (e.g., 'books', 'papers', 'exams')", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the category', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(help_text="Unique identifier for the organization (e.g., 'soa', 'ifoa', 'cas')", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the organization', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.CharField(help_text="Unique identifier for the resource type (e.g., 'free', 'premium', 'books')", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the resource type', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Resource Type',
                'verbose_name_plural': 'Resource Types',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the resource', max_length=255)),
                ('author', models.CharField(help_text='Author(s) of the resource', max_length=255)),
                ('description', models.TextField(help_text='Description of the resource')),
                ('file', models.FileField(blank=True, help_text='Upload the resource file', null=True, upload_to=resources.models.resource_file_path)),
                ('download_url', models.URLField(blank=True, help_text='External URL for downloading the resource (if not uploaded)', max_length=500, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the resource', null=True, upload_to=resources.models.resource_cover_path)),
                ('is_premium', models.BooleanField(default=False, help_text='Indicates if the resource is premium')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the resource is active')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times the resource has been viewed')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times the resource has been downloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the resource was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the resource was last updated')),
                ('category', models.ForeignKey(help_text='Category of the resource', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization associated with the resource', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.organization')),
                ('resource_type', models.ForeignKey(help_text='Type of the resource', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.resourcetype')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'indexes': [models.Index(fields=['title', 'author'], name='resources_r_title_7617bc_idx'), models.Index(fields=['category'], name='resources_r_categor_499e30_idx'), models.Index(fields=['resource_type'], name='resources_r_resourc_71dcaf_idx'), models.Index(fields=['organization'], name='resources_r_organiz_e19d76_idx')],
            },
        ),
    ]
